// Русская локализация

tinyMCE.addToLang('',{
bold_desc : 'Полужирный (Ctrl+B)',
italic_desc : 'Курсив (Ctrl+I)',
underline_desc : 'Подчеркнутый (Ctrl+U)',
striketrough_desc : 'Перечеркнутый',
justifyleft_desc : 'По левому краю',
justifycenter_desc : 'По центру',
justifyright_desc : 'По правому краю',
justifyfull_desc : 'По ширине',
bullist_desc : 'Маркированный список',
numlist_desc : 'Нумерованный список',
outdent_desc : 'Уменьшить отступ',
indent_desc : 'Увеличить отступ',
undo_desc : 'Отменить (Ctrl+Z)',
redo_desc : 'Вернуть (Ctrl+Y)',
link_desc : 'Вставить/редактировать ссылку',
unlink_desc : 'Удалить ссылку',
image_desc : 'Вставить/редактировать изображение',
cleanup_desc : 'Вычистить захламленный код',
focus_alert : 'Окно редактора должно быть в фокусе для использования этой команды.',
edit_confirm : 'Вы хотите использовать Визуальный Редактор для этого редактируемого поля ?',
insert_link_title : 'Вставить/редактировать ссылку',
insert : 'Вставить',
update : 'Обновить',
cancel : 'Выход',
insert_link_url : 'URL ссылки',
insert_link_target : 'Открывать ссылку',
insert_link_target_same : 'в своём окне',
insert_link_target_blank : 'в новом окне',
insert_image_title : 'Вставить/редактировать изображение',
insert_image_src : 'URL изображения',
insert_image_alt : 'Описание изображения',
help_desc : 'Помощь',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Копировать/Вырезать/Вставить не доступно для Mozilla и Firefox.\nХотите больше узнать о причине ?',
popup_blocked : 'К сожалению Ваш блокировщик всплывающих окон отключил функциональное окно для этого инструмента. Вы должны отключить блокировщик всплывающих окон для этого сайта, чтобы использовать данный инструмент.'
});
