// Русская локализация

tinyMCE.addToLang('style',{
title : 'Редактор CSS стилей',
styleinfo_desc : 'Редактор CSS стилей',
apply : 'Применить',
text_tab : 'Текст',
background_tab : 'Фон',
block_tab : 'Блок',
box_tab : 'Бокс',
border_tab : 'Граница',
list_tab : 'Список',
positioning_tab : 'Позиционирование',
text_props : 'Текст',
text_font : 'Шрифт',
text_size : 'Размер',
text_weight : 'Насыщенность',
text_style : 'Стиль',
text_variant : 'Капитель',
text_lineheight : 'Межстрочное расст.',
text_case : 'Регистр',
text_color : 'Цвет',
text_decoration : 'Оформление',
text_overline : 'линия над текстом',
text_underline : 'подчеркнутый',
text_striketrough : 'перечеркнутый',
text_blink : 'мигающий',
text_none : 'нет',
background_color : 'Цвет фона',
background_image : 'Фоновый рисунок',
background_repeat : 'Повторение фона',
background_attachment : 'Прокрутка фона',
background_hpos : 'Гориз. позиция',
background_vpos : 'Верт. позиция',
block_wordspacing : 'Инт. между словами',
block_letterspacing : 'Инт. между буквами',
block_vertical_alignment : 'Верт. выравнивание',
block_text_align : 'Выравн. текста',
block_text_indent : 'Отступ перв. строки',
block_whitespace : 'Пробелы',
block_display : 'Показывать',
box_width : 'Ширина',
box_height : 'Высота',
box_float : 'Floating',
box_clear : 'Clear',
padding : 'Padding',
same : 'Одно для всех',
top : 'Сверху',
right : 'Справа',
bottom : 'Снизу',
left : 'Слева',
margin : 'Margin',
style : 'Стиль',
width : 'Ширина',
height : 'Высота',
color : 'Цвет',
list_type : 'Тип',
bullet_image : 'Иконки списка',
position : 'Позиция',
positioning_type : 'Тип',
visibility : 'Видимость',
zindex : 'Z-индекс',
overflow : 'Переполнение',
placement : 'Placement',
clip : 'Clip'
});
