// Русская локализация

tinyMCE.addToLang('',{
theme_style_select : '-- Стили --',
theme_code_desc : 'Редактировать HTML',
theme_code_title : 'Редактор HTML',
theme_code_wordwrap : 'Перенос слов',
theme_sub_desc : 'Подстрочный',
theme_sup_desc : 'Надстрочный',
theme_hr_desc : 'Вставить горизонтальную линию',
theme_removeformat_desc : 'Убрать форматирование',
theme_custom1_desc : 'Для собственного описания',
insert_image_border : 'Граница',
insert_image_dimensions : 'Размеры',
insert_image_vspace : 'Вертикальный отступ',
insert_image_hspace : 'Горизонтальный отступ',
insert_image_align : 'Выравнивание',
insert_image_align_default : '-- Не задано --',
insert_image_align_baseline : 'По линии',
insert_image_align_top : 'Сверху',
insert_image_align_middle : 'По середине',
insert_image_align_bottom : 'Снизу',
insert_image_align_texttop : 'Текст по верху',
insert_image_align_absmiddle : 'Абсолютно по середине',
insert_image_align_absbottom : 'Абсолютно снизу',
insert_image_align_left : 'Слева',
insert_image_align_right : 'Справа',
theme_font_size : '-- Размер --',
theme_fontdefault : '-- Шрифт --',
theme_block : '-- Формат --',
theme_paragraph : 'Параграф',
theme_div : 'Слой',
theme_address : 'Адрес',
theme_pre : 'Пре-форматированный',
theme_h1 : 'Заголовок 1',
theme_h2 : 'Заголовок 2',
theme_h3 : 'Заголовок 3',
theme_h4 : 'Заголовок 4',
theme_h5 : 'Заголовок 5',
theme_h6 : 'Заголовок 6',
theme_blockquote : 'Блок цитирования',
theme_code : 'Код',
theme_samp : 'Образец кода',
theme_dt : 'Список определений ',
theme_dd : 'Описание списка определений',
theme_colorpicker_title : 'Выберите цвет',
theme_colorpicker_apply : 'Применить',
theme_forecolor_desc : 'Выбрать цвет текста',
theme_backcolor_desc : 'Выбрать цвет фона',
theme_charmap_title : 'Выберите спецсимвол',
theme_charmap_desc : 'Вставить спецсимвол',
theme_visualaid_desc : 'Отображать сетку таблицы',
insert_anchor_title : 'Вставить/редактировать якорь',
insert_anchor_name : 'Имя якоря',
theme_anchor_desc : 'Вставить/редактировать якорь',
theme_insert_link_titlefield : 'Заголовок',
theme_clipboard_msg : 'Копировать/Вырезать/Вставить не доступно для Mozilla и Firefox.\nХотите больше узнать о причине ?',
theme_path : 'Путь',
cut_desc : 'Вырезать',
copy_desc : 'Копировать',
paste_desc : 'Вставить',
link_list : 'Список ссылок',
image_list : 'Список изображений',
browse : 'Просмотр',
image_props_desc : 'Свойства изображения',
newdocument_desc : 'Новый документ',
class_name : 'Класс',
newdocument : 'Вы уверены, что хотите очистить всё предыдущее содержимое ?',
about_title : 'О редакторе TinyMCE',
about : 'О программе',
license : 'Лицензия',
plugins : 'Плагины',
plugin : 'Плагин',
author : 'Автор',
version : 'Версия',
loaded_plugins : 'Загруженные плагины',
help : 'Помощь',
not_set : '-- Не задано --',
close : 'Закрыть',
toolbar_focus : 'Перейти к кнопкам инструментов - Alt+Q, перейти к редактору - Alt-Z, перейти к пути элемента - Alt-X',
invalid_data : 'Ошибка: введены неправильные значения, они помечены красным цветом.',
//JCE Sepcific
name : 'Имя',
ok : 'Ok',
unique : 'Создать уникальный файл',
overwrite : 'Перезаписать существующий файл',
folder : 'Каталог',
file : 'Файл',
upload : 'Загрузка',
new_folder : 'Новый каталог',
rename_file : 'Переименовать файл',
rename_folder : 'Переименовать каталог',
delete_file_alert : 'Удалить файл(ы) ?',
delete_folder_alert : 'Удалить каталог ?',
rename_alert : 'Переименование каталогов или файлов испортит существующие ссылки. Продолжить ?',
files_select : 'Файлы выбраны',
template_colors : 'Цвета шаблона',
standard_colors : 'Стандартные цвета'
});
